name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install prerequisites
      run: sudo apt-get install -y verilator
    - uses: actions/checkout@v4
    - name: Build Release
      run: make -j12
    - name: Simulate
      run: ./obj_dir/Vtop
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Simulation Artifacts
        path: |
            toptrace.vcd
